-- MySQL Script generated by MySQL Workbench
-- Tue Aug 16 09:52:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema primeiro_banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema primeiro_banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `primeiro_banco` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `primeiro_banco` ;

-- -----------------------------------------------------
-- Table `primeiro_banco`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_banco`.`Cliente` (
  `Nome` VARCHAR(45) NULL,
  `CPF` INT NULL,
  `RG` VARCHAR(45) NULL,
  `Clientecol` INT NULL,
  `Endereco` VARCHAR(45) NULL,
  `idCliente` INT NOT NULL,
  `ID-Animais_Cliente` INT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `primeiro_banco`.`Animais_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_banco`.`Animais_Cliente` (
  `ID-Animal` INT NULL,
  `Quantidade` INT NULL,
  `ID-Animais_Cliente` INT NOT NULL,
  PRIMARY KEY (`ID-Animais_Cliente`),
  CONSTRAINT `fk_Animais_Cliente_Cliente1`
    FOREIGN KEY (`ID-Animais_Cliente`)
    REFERENCES `primeiro_banco`.`Cliente` (`ID-Animais_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `primeiro_banco`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_banco`.`Animal` (
  `idAnimal` INT NOT NULL,
  `Especie` VARCHAR(45) NULL,
  `Raca` VARCHAR(45) NULL,
  `Tamanho` FLOAT NULL,
  `Nome` VARCHAR(45) NULL,
  `Peso` FLOAT NULL,
  `Idade` INT NULL,
  `ID-Agendamento` INT NULL,
  `ID-Animais_Cliente` INT NULL,
  PRIMARY KEY (`idAnimal`),
  CONSTRAINT `fk_Animal_Animais_Cliente1`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `primeiro_banco`.`Animais_Cliente` (`ID-Animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `primeiro_banco`.`Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_banco`.`Agendamento` (
  `idAgendamento` INT NOT NULL,
  `Dia` DATE NULL,
  `Horario` TIME NULL,
  `ID-Servocos` INT NULL,
  `ID-Animal` INT NULL,
  `Limite_Agendamento` INT NULL,
  PRIMARY KEY (`idAgendamento`),
  INDEX `fk_Agendamento_Animal1_idx` (`ID-Animal` ASC) VISIBLE,
  CONSTRAINT `fk_Agendamento_Animal1`
    FOREIGN KEY (`ID-Animal`)
    REFERENCES `primeiro_banco`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `primeiro_banco`.`Funcioario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_banco`.`Funcioario` (
  `idFuncioario` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `RG` INT NULL,
  `CPF` INT NULL,
  `Valor_salario` INT NULL,
  `Ocupacao` VARCHAR(45) NULL,
  `Idade` INT NULL,
  `Contato` INT NULL,
  PRIMARY KEY (`idFuncioario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `primeiro_banco`.`Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_banco`.`Servicos` (
  `idServicos` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Preco` FLOAT NULL,
  `ID-Funcionario` INT NULL,
  `Funcioario_idFuncioario` INT NOT NULL,
  PRIMARY KEY (`idServicos`),
  INDEX `fk_Servicos_Funcioario1_idx` (`Funcioario_idFuncioario` ASC) VISIBLE,
  CONSTRAINT `fk_Servicos_Agendamento1`
    FOREIGN KEY (`idServicos`)
    REFERENCES `primeiro_banco`.`Agendamento` (`idAgendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicos_Funcioario1`
    FOREIGN KEY (`Funcioario_idFuncioario`)
    REFERENCES `primeiro_banco`.`Funcioario` (`idFuncioario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `primeiro_banco`.`Servicos_has_Funcioario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primeiro_banco`.`Servicos_has_Funcioario` (
  `Servicos_idServicos` INT NOT NULL,
  `Funcioario_idFuncioario` INT NOT NULL,
  PRIMARY KEY (`Servicos_idServicos`, `Funcioario_idFuncioario`),
  INDEX `fk_Servicos_has_Funcioario_Funcioario1_idx` (`Funcioario_idFuncioario` ASC) VISIBLE,
  INDEX `fk_Servicos_has_Funcioario_Servicos1_idx` (`Servicos_idServicos` ASC) VISIBLE,
  CONSTRAINT `fk_Servicos_has_Funcioario_Servicos1`
    FOREIGN KEY (`Servicos_idServicos`)
    REFERENCES `primeiro_banco`.`Servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicos_has_Funcioario_Funcioario1`
    FOREIGN KEY (`Funcioario_idFuncioario`)
    REFERENCES `primeiro_banco`.`Funcioario` (`idFuncioario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
